### ISSUE TITLE
covariance types

### ISSUE THREAD

**Issue by skyee1** [m-clark/mixed-models-with-R#23]
Thank you for such a nice Package.
1) Can you add some special covariance structures? For example, FA0(2) or CSH(Heterogeneous Compound Symmetry).
2) This package does not seem to support ANOVA.

**Comment by m-clark** [comment]
Hi @skyee1, this repo is for a document that only covers mixed modeling, it doesn't provide modeling functions. If you're specifically interested in the lme4 functionality, I can refer you to that [repo](https://github.com/lme4/lme4), and you are right, but I do talk about that a bit in the [residual structure section](https://m-clark.github.io/mixed-models-with-R/extensions.html#residual-structure).  lme4 does have anova functionality though.

If you meant to refer to my [mixedup](https://github.com/m-clark/mixedup) package, it only extracts the model output from other packages, it doesn't do any modeling itself, and only some of the supported packages support that residual correlation/heterogenous variances. I have some very limited support to extract residual cor info from nlme, brms, and glmmTMB (see [here](https://m-clark.github.io/mixedup/reference/extract_cor_structure.html)).  I don't have any summary functions to convert anova output to tibbles (again though, the underlying package would need to have that functionality), and you are welcome to open an issue on the mixedup package repository for that if you like.
