### ISSUE TITLE
Related code examples

### ISSUE THREAD

**Issue by alepistola** [m-clark/mixed-models-with-R#25]
Hi Clark, 

first of all thank you for this precious guides. I just want to ask you if there is the possibility to publish the related R snippets code (eg all the plots codes). Thanks in advance

**Comment by m-clark** [comment]
Howdy! While I don't have any plans to publish extraneous related code for the doc, all the code is available on the repo.  Just look at the [associated chapter .Rmd files](https://github.com/m-clark/mixed-models-with-R) for a chapter that has a plot you're interested in.

Just a warning: that doc has been around a while, and you may see some correspondingly old code that I would not recommend if I were doing it from scratch today.

**Comment by alepistola** [comment]
Ok it makes sense! Thanks anyway for the fast answer
